theme: jekyll-theme-minimal
title: NeqSim
name: Even Solbraa
email: Even.Solbraa@ntnu.no
description: NeqSim is a library for estimation of behaviour and properties of fluids. NeqSim is available for free use and distributed as open source under the Apache-2.0 licence.
logo: figures/logonotext.PNG
repository: https://github.com/equinor/neqsim
